<?xml version="1.0"?>
<package format="3">
  <name>learm_kinematics</name>
  <version>0.1.0</version>
  <description>FK/IK utilities and a simple slider teleop for LeArm</description>

  <maintainer email="you@example.com">Sumayya</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>

  <!-- Optional: only if you actually use it at runtime -->
  <exec_depend>tf_transformations</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
